const express = require('express')
const routesActions = require('../actions/routes_actions.js')
const router = express.Router()

router.put('/user',routesActions.signup)
router.post('/user',routesActions.login)
router.put('/soccer-event',routesActions.createSoccerEvent)
router.put('/basket-event',routesActions.createBasketEvent)
router.get('/soccer-event',routesActions.getSoccerEvents)
router.put('/buletin',routesActions.createBuletin)
router.post('/deposito',routesActions.deposit)
router.post('/levantamento',routesActions.raise)
router.post('/transaction-user',routesActions.getUserTransactions)
router.get('/buletin-user',routesActions.getUserBuletinHistory)
router.put('/betType',routesActions.createBetType)
router.put('/sport',routesActions.createSport)
router.get('/esporte',routesActions.getSports)
router.put('/evento-coletivo',routesActions.createEventColetive)
router.get('/tipo-de-aposta-estrutura',routesActions.getBetTypeStructureBySport)
router.put('/equipa',routesActions.createTeam)
router.put('/jogador',routesActions.createPlayer)
router.post('/eventos-desporto-coletivo',routesActions.getSportEventsColetive)
router.get('/eventos-outras-casas',routesActions.getEventsOthers)
router.post('/popular-eventos',routesActions.eventsPopulate)
router.get('/utilizador',routesActions.getUserData)
router.get('/boletim',routesActions.getBuletin)
router.post('/apostas-do-boletim',routesActions.getBetsByBuletin)

module.exports = router